### ISSUE TITLE
dash '-' in the version number

### ISSUE THREAD

**Issue by attilalaszlo** [unindented/electron-installer-redhat#36]
In rpm files you are not allowed to use dash in the version number.
According to this:
http://www.rpm.org/max-rpm/ch-rpm-file-format.html

In the https://github.com/unindented/electron-installer-debian package this is already solved issue:

in: /src/installer.js
<code>
// Use '~' on pre-releases for proper debain version ordering.
// See https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version
version: (pkg.version || '0.0.0').replace(/(\d)[_.-+]?((RC|rc|pre|dev|beta|alpha)[_.-+]?\d*)$/, '$1~$2')
</code>

It's neccessary for this package also.

**Comment by unindented** [comment]
Cool, can you create a pull request?

**Comment by jacobq** [comment]
I just ran into this today. Seeing as this is quite old in software time now I'm going to start working on a PR. If someone else is already on it please let me know.

**Comment by jacobq** [comment]
I think this can be closed since it is addressed by PR #49

**Comment by unindented** [comment]
Thanks @jacobq!
