### ISSUE TITLE
Add support for creating src rpms and spec files.

### ISSUE THREAD

**Issue by Dark-Passenger** [unindented/electron-installer-redhat#70]
This will allow for merging packages directly to fedora or rhel or even centos repositories.

I will try to send a PR for this but I don't have any experience with js and electron apps.

Note : I am filing this because it's used by etcher for packaging rpms and this will allow for official packages.

**Comment by unindented** [comment]
I don't have much experience with src rpms, so I'll await your PR. Thanks!

**Comment by Dark-Passenger** [comment]
@unindented and the problem is my js knowledge is non-existent.

From what i understood of your code its actually pretty straightforward to add support for source rpms and moving spec files.

all you need to change is run rpmbuild with -ba instead of -bb.
and then copy the src rpm from SRPMS directory to the destination directory.
and the same is true for spec files.

**Comment by Dark-Passenger** [comment]
But since I can't do this now ... will close it. :)
