### ISSUE TITLE
Installer seems to disregard config file settings

### ISSUE THREAD

**Issue by fmarzocca** [unindented/electron-installer-redhat#79]
**What version of `electron-installer-redhat` are you using?**
0.5.0

**What version of `node` and `npm` are you using?**
node 4.2.6 npm 3.5.2

**What operating system are you using?**
Linux Mint 18.3

I have a weird behaviour...

This is my redhat.json config file:
```
{
  "dest": "release-builds/",
  "icon": "icons/icon-512x512.png",
  "name": "meteosurf-desktop",
  "bin": "myapp-desktop",
  "categories": [
    "Network"
  ]
}
```
I am calling the installer with this line in package.json:

`"rpm-installer": "electron-installer-redhat --src release-builds/meteosurf-desktop-linux-x64/ --dest release-builds --arch x86_64 --config: redhat.json",`

The problem is that the installer completely disregards my config settings, and it uses another name (My App) which I don't know where it takes from. The result is a broken link between /usr/bin and /usr/share/myapp-desktop

**Comment by fcastilloec** [comment]
you're calling the installer with `--config: redhat.json` where it should read `--config redhat.json` (without the colon).
Please read all the documentation before posting issues.
`options.name` is for the Name field of the spec file, make sure you also change `options.bin`.
What I suggest is keep a tidy `package.json`, where `productName` will be used as the default by this installer, and use the latest `electron-packager` where you specify the executable name to be equal to the `productName`, following the same naming conventions.
You could see a similar behaivor for the [Debian installer](https://github.com/unindented/electron-installer-debian/issues/107#issuecomment-334215509)
