### ISSUE TITLE
Error "Need to fill license in (main package)"

### ISSUE THREAD

**Issue by Miguel-Gen** [unindented/electron-installer-redhat#83]
**What version of `electron-installer-redhat` are you using?**
0.5.0
**What version of `node` and `npm` are you using?**
Nodejs: v9.4.0 | Npm: 5.6.0
**What operating system are you using?**
Elementary OS based in Ubuntu
**Can you compile the [WhatsApp-Linux](https://github.com/Miguel-Gen/Whatsapp-For-Linux) successfully?**

I can't compile the app to .rpm.

**If not, paste here the output of the following commands:**

Error: Error executing command (1): 
rpmbuild -bb /tmp/electron-11811-3143-jj2bz6.9l16/WhatsApp-Linux_1.0.0_x86_64/SPECS/WhatsApp-Linux.spec --target x86_64
error: el campo License debe estar presente en el paquete: (main package)

```
$ git clone https://github.com/Miguel-Gen/Whatsapp-For-Linux.git
$ cd electron-installer-redhat/example
$ DEBUG='electron-installer-redhat' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-redhat`.**
En el Package.json:

`"rpm64": "electron-installer-redhat --src release-builds/WhatsApp-Linux-linux-x64/ --arch x86_64 --config config.json"`

En el config.json:

`
  "dest": "release_builds/",
  "icon": "assets/png/icon.png",
  "categories": [
    "Utility"
  ]
}`

**What did you expect to happen?**

That compile to RPM.
**What actually happened?**

I can't compile to RPM because the console say "Need fill license in (main package). I don't know what is main package.

**Comment by fcastilloec** [comment]
The issue section is for reporting bugs or asking for features. This post is just asking for help understanding how to build a package. There are other places to look for help. You could google the error, which will show you tons of results about it. You should at least read our README, before posting here. Here's a link to the [license section](https://github.com/unindented/electron-installer-redhat#optionslicense). Nonetheless, just add a LICENSE file to your project or at least the option that I pointed out from the readme.
